apiVersion: v1
kind: ReplicationController
metadata:
  name: getter
spec:
  replicas: 0
  selector:
    role: getter
  template:
    metadata:
      labels:
        role: getter
    spec:
      containers:
      - name: getter
        image: lwr20/getter:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: TIMEOUT
          value: ".1"
        - name: SLEEPTIME
          value: "0"
        - name: ENDSLEEP
          value: "36000"
